serverAddr = "frp.ai-lab.top"
serverPort = 7000
auth.method = "token"
auth.token = "13579acb"
[[proxies]]
name = "sr21-bv"
type = "tcp"
localIP = "127.0.0.1"
localPort = 2334
remotePort = 2334

[[proxies]]
name = "sr21-bv-mon"
type = "tcp"
localIP = "127.0.0.1"
localPort = 2434
remotePort = 2434